# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-25 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('descriptions', models.TextField(verbose_name='Informations')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('likes', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
