# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-26 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_post', '0008_auto_20181126_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
    ]
